// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/callback": {
            "get": {
                "description": "GitHub認証後にJWTをHttpOnly Cookieへ保存し、フロントへリダイレクトします。",
                "tags": [
                    "auth"
                ],
                "summary": "GitHub OAuthコールバック",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GitHub OAuth code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "get": {
                "description": "GitHubの認可画面へリダイレクトします。",
                "tags": [
                    "auth"
                ],
                "summary": "GitHub OAuthログインを開始",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/character/job": {
            "patch": {
                "description": "ログイン中のユーザーが所有するキャラクターの職業を変更し、ステータスを初期化します。",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "character"
                ],
                "summary": "キャラクターを転職させる",
                "parameters": [
                    {
                        "description": "転職するキャラクターと職業",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.JobChangeReq"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/character/status": {
            "patch": {
                "description": "指定したXPを消費し、1つ以上のステータスを加算します。ステータス加算値の合計はxpと一致する必要があります。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "character"
                ],
                "summary": "XPを消費してキャラクターのステータスを強化",
                "parameters": [
                    {
                        "description": "キャラクターID、消費XP、加算するステータス",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.StatusEditCharacterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.StatusEditCharacterRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/game/syncCommit": {
            "get": {
                "description": "GitHub の PushEvent を取得し、ゲームデータのコミット数を更新します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "GitHub のコミット数を同期",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.SyncGithubCommitsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "ログイン中のユーザーを取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal server error"
                }
            }
        },
        "http.SyncGithubCommitsResponse": {
            "type": "object",
            "properties": {
                "checked_since": {
                    "type": "string"
                },
                "checked_until": {
                    "type": "string"
                },
                "github_name": {
                    "type": "string"
                },
                "matched_push_event_count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "new_commit_count": {
                    "type": "integer"
                },
                "total_commits": {
                    "type": "integer"
                },
                "updated": {
                    "type": "boolean"
                }
            }
        },
        "presenter.JobChangeReq": {
            "type": "object",
            "required": [
                "id",
                "job"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "job": {
                    "type": "string",
                    "example": "Hero"
                }
            }
        },
        "presenter.StatusEditCharacterReq": {
            "type": "object",
            "required": [
                "id",
                "xp"
            ],
            "properties": {
                "agi": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "atk": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 2
                },
                "def": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 3
                },
                "hp": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "luk": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "matk": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "mdef": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "xp": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 5
                }
            }
        },
        "presenter.StatusEditCharacterRes": {
            "type": "object",
            "properties": {
                "agi": {
                    "type": "integer"
                },
                "atk": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "def": {
                    "type": "integer"
                },
                "hp": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "job": {
                    "type": "string"
                },
                "luk": {
                    "type": "integer"
                },
                "matk": {
                    "type": "integer"
                },
                "mdef": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "xp": {
                    "type": "integer"
                }
            }
        },
        "presenter.UserResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "github_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Backend API",
	Description:      "GitHub OAuthとゲームデータを提供するAPIです。認証にはHttpOnly Cookieを使用します。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
